name: Build AbyssVideoDownloader

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build AbyssVideoDownloader
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Clone Repository
        run: |
          git clone https://github.com/abdlhay/AbyssVideoDownloader.git
          cd AbyssVideoDownloader
          
      - name: Make Gradle Executable
        run: chmod +x AbyssVideoDownloader/gradlew

      - name: Build AbyssVideoDownloader
        run: |
          cd AbyssVideoDownloader
          ./gradlew build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: AbyssVideoDownloader-v${{ github.run_number }}
          name: AbyssVideoDownloader-v${{ github.run_number }}
          files: AbyssVideoDownloader/build/libs/abyss-dl.jar
          draft: true
